#!/usr/bin/env python3
"""Run Línea 6 with Qwen/Gemma/Llama inside one MiroFish simulation.

Default mode is a no-key dry run: it builds the deterministic round-robin model
map against synthetic or prepared agent configs and validates routing logic.

Paid `--execute` mode expects a running backend (or `--start-backend`) and API
keys in env. It prepares the case, writes a generated by_agent_id model map into
the simulation directory, starts the Reddit simulation with `model_map_path`, and
validates that all three models actually appear in `llm_telemetry.jsonl`.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import signal
import subprocess
import sys
import time
from collections import Counter, defaultdict
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence

import yaml

REPO = Path(__file__).resolve().parents[1]
BACKEND = REPO / "backend"


def backend_python() -> Path:
    candidates = [
        BACKEND / ".venv/Scripts/python.exe",
        BACKEND / ".venv/bin/python",
    ]
    for candidate in candidates:
        if candidate.exists():
            return candidate
    return Path(sys.executable)


PY = backend_python()
DEFAULT_CASE_DIR = REPO / "backtesting/case-b-s2-bolivia-2025-runoff"
DEFAULT_CASE = DEFAULT_CASE_DIR / "seed_T3_clean.md"
DEFAULT_OUT_ROOT = REPO / "runs/linea6"
DEFAULT_REQUIREMENT = """# Question

Con la informacion disponible en el paquete de evidencia provisto, predecir quien ganara el balotaje presidencial de Bolivia del 19 de octubre de 2025.

Responder exclusivamente en espanol.

La respuesta debe:
- identificar desde la evidencia cuales son los dos candidatos competitivos del balotaje;
- elegir una prediccion principal unica, sin responder empate;
- estimar el porcentaje de voto de los dos candidatos competitivos y de otros/blanco/nulo;
- estimar el margen entre el ganador predicho y el segundo candidato en puntos;
- justificar la prediccion usando solo evidencia del contexto entregado;
- explicar como pesan la crisis economica, el colapso del MAS, la sorpresa de primera vuelta, el contraste de plataformas y la encuesta tardia;
- mencionar factores de incertidumbre;
- no usar informacion posterior a la fecha maxima del paquete.
"""

# Make app.services.* and tools.mirofish_headless importable without installing.
sys.path.insert(0, str(BACKEND))
sys.path.insert(0, str(REPO))

from app.services.model_router import ModelRouter, load_model_map  # type: ignore[import-not-found]  # noqa: E402
from tools.mirofish_headless import APIClient, write_json  # noqa: E402


@dataclass(frozen=True)
class RouteModel:
    label: str
    provider: str
    model: str
    base_url: str
    base_url_env: str
    api_key_env: str


ROUTE_MODELS: Sequence[RouteModel] = (
    RouteModel(
        label="qwen",
        provider="openrouter",
        model="qwen/qwen3-8b",
        base_url="https://openrouter.ai/api/v1",
        base_url_env="OPENROUTER_BASE_URL",
        api_key_env="OPENROUTER_API_KEY",
    ),
    RouteModel(
        label="gemma",
        provider="deepinfra",
        model="google/gemma-3-27b-it",
        base_url="https://api.deepinfra.com/v1/openai",
        base_url_env="DEEPINFRA_BASE_URL",
        api_key_env="DEEPINFRA_API_KEY",
    ),
    RouteModel(
        label="llama",
        provider="deepinfra",
        model="meta-llama/Llama-3.3-70B-Instruct-Turbo",
        base_url="https://api.deepinfra.com/v1/openai",
        base_url_env="DEEPINFRA_BASE_URL",
        api_key_env="DEEPINFRA_API_KEY",
    ),
)
EXPECTED_MODELS = {m.model for m in ROUTE_MODELS}
TERMINAL_RUN_STATUSES = {"completed", "failed", "stopped", "cancelled", "error"}
TERMINAL_TASK_STATUSES = {"completed", "failed", "cancelled", "error"}


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def case_slug(path: Path) -> str:
    return path.stem.replace("seed_", "").replace("assembled_", "").lower()


def read_json(path: Path) -> Dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def model_layer(model: RouteModel, *, temperature: float = 0.7) -> Dict[str, Any]:
    return {
        "provider": model.provider,
        "model": model.model,
        "base_url": model.base_url,
        "base_url_env": model.base_url_env,
        "api_key_env": model.api_key_env,
        "temperature": temperature,
        "seed": None,
    }


def sorted_agent_ids(agent_configs: Sequence[Dict[str, Any]]) -> List[int]:
    ids: List[int] = []
    for idx, cfg in enumerate(agent_configs):
        ids.append(int(cfg.get("agent_id", idx)))
    return sorted(ids)


def build_round_robin_model_map(agent_configs: Sequence[Dict[str, Any]]) -> Dict[str, Any]:
    """Deterministically assign sorted agent_ids Qwen, Gemma, Llama, repeat."""
    by_agent_id: Dict[int, Dict[str, Any]] = {}
    for pos, agent_id in enumerate(sorted_agent_ids(agent_configs)):
        by_agent_id[agent_id] = model_layer(ROUTE_MODELS[pos % len(ROUTE_MODELS)])
    return {
        "version": 1,
        "default": model_layer(ROUTE_MODELS[0]),
        "fallback": {"enabled": False},
        "by_agent_id": by_agent_id,
    }


def write_model_map(path: Path, model_map: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(model_map, sort_keys=False, allow_unicode=True), encoding="utf-8")


def synthetic_agent_configs(n: int = 12) -> List[Dict[str, Any]]:
    roles = [
        "PollingInstitution",
        "Organization",
        "MediaOutlet",
        "GovernmentExecutive",
        "FiscalConsultancy",
        "Person",
    ]
    return [
        {
            "agent_id": i,
            "entity_type": roles[i % len(roles)],
            "active_hours": list(range(8, 23)),
            "activity_level": 0.75,
        }
        for i in range(n)
    ]


def load_agent_configs_from_sim_dir(sim_dir: Path) -> List[Dict[str, Any]]:
    config_path = sim_dir / "simulation_config.json"
    if not config_path.exists():
        raise FileNotFoundError(f"simulation_config.json not found in {sim_dir}")
    config = read_json(config_path)
    agent_configs = config.get("agent_configs") or []
    if not agent_configs:
        profiles_path = sim_dir / "reddit_profiles.json"
        if profiles_path.exists():
            profiles = json.loads(profiles_path.read_text(encoding="utf-8"))
            agent_configs = [
                {"agent_id": i, "entity_type": p.get("entity_type") or p.get("role")}
                for i, p in enumerate(profiles)
            ]
    if not agent_configs:
        raise ValueError(f"No agent_configs or reddit_profiles.json agents found in {sim_dir}")
    return agent_configs


def route_audit_from_map(map_path: Path, agent_configs: Sequence[Dict[str, Any]]) -> List[Dict[str, Any]]:
    router = ModelRouter(load_model_map(str(map_path)))
    roles = {int(cfg.get("agent_id", idx)): cfg.get("entity_type") for idx, cfg in enumerate(agent_configs)}
    return [router.resolve(agent_id, roles.get(agent_id)).to_audit() for agent_id in sorted_agent_ids(agent_configs)]


def write_jsonl(path: Path, rows: Iterable[Dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        for row in rows:
            f.write(json.dumps(row, ensure_ascii=False) + "\n")


def parse_jsonl(path: Path) -> List[Dict[str, Any]]:
    if not path.exists():
        return []
    rows: List[Dict[str, Any]] = []
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip()
        if not line:
            continue
        rows.append(json.loads(line))
    return rows


def summarize_telemetry(telemetry_path: Path) -> Dict[str, Any]:
    rows = parse_jsonl(telemetry_path)
    by_model: Dict[str, Dict[str, Any]] = defaultdict(lambda: {"calls": 0, "tokens_in": 0, "tokens_out": 0, "errors": 0})
    providers: set[str] = set()
    errors = 0
    parse_errors = 0
    for rec in rows:
        model = rec.get("model") or "unknown"
        providers.add(str(rec.get("provider") or "unknown"))
        slot = by_model[model]
        slot["calls"] += 1
        slot["tokens_in"] += int(rec.get("tokens_in") or 0)
        slot["tokens_out"] += int(rec.get("tokens_out") or 0)
        if rec.get("error"):
            errors += 1
            slot["errors"] += 1
        if rec.get("output_valid_json") is False:
            parse_errors += 1
    return {
        "llm_calls": len(rows),
        "tokens_in": sum(v["tokens_in"] for v in by_model.values()),
        "tokens_out": sum(v["tokens_out"] for v in by_model.values()),
        "errors": errors,
        "parse_errors": parse_errors,
        "models": sorted(m for m in by_model if m != "unknown"),
        "providers": sorted(providers),
        "by_model": dict(sorted(by_model.items())),
    }


def validate_effective_trimodel(audit_path: Path, telemetry_path: Path) -> Dict[str, Any]:
    audit_rows = parse_jsonl(audit_path)
    telemetry_summary = summarize_telemetry(telemetry_path)
    assigned = {row.get("model") for row in audit_rows if row.get("model")}
    called = set(telemetry_summary["models"])
    return {
        "expected_models": sorted(EXPECTED_MODELS),
        "assigned_models": sorted(assigned),
        "called_models": sorted(called),
        "missing_assigned_models": sorted(EXPECTED_MODELS - assigned),
        "missing_called_models": sorted(EXPECTED_MODELS - called),
        "is_assigned_trimodel": EXPECTED_MODELS.issubset(assigned),
        "is_effective_trimodel": EXPECTED_MODELS.issubset(called),
        "telemetry_summary": telemetry_summary,
    }


def write_fake_telemetry(path: Path) -> None:
    rows = []
    for i, model in enumerate(ROUTE_MODELS):
        rows.append(
            {
                "timestamp": utc_now(),
                "round": i,
                "agent_id": i,
                "role": "dry_run_fake",
                "provider": model.provider,
                "model": model.model,
                "temperature": 0.7,
                "prompt_hash": f"dry-run-prompt-{i}",
                "response_hash": f"dry-run-response-{i}",
                "tokens_in": 10 + i,
                "tokens_out": 5 + i,
                "latency_ms": 0,
                "cost_usd_est": 0.0,
                "output_valid_json": True,
                "error": None,
                "leak_flags": ["dry_run_fake_telemetry_not_model_output"],
            }
        )
    write_jsonl(path, rows)


def dry_run(args: argparse.Namespace, out_root: Path) -> int:
    out_root.mkdir(parents=True, exist_ok=True)
    cases = expand_cases(args)
    results = []
    for case_file in cases:
        slug = case_slug(case_file)
        out = out_root / slug
        if args.prepared_sim_dir:
            agent_configs = load_agent_configs_from_sim_dir(Path(args.prepared_sim_dir))
            source = str(args.prepared_sim_dir)
        else:
            agent_configs = synthetic_agent_configs(args.synthetic_agents)
            source = "synthetic_agent_configs"
        model_map = build_round_robin_model_map(agent_configs)
        map_path = out / "model_map.generated.yaml"
        write_model_map(map_path, model_map)
        audit_rows = route_audit_from_map(map_path, agent_configs)
        audit_path = out / "model_routing_audit.dryrun.jsonl"
        write_jsonl(audit_path, ({"timestamp": utc_now(), **row} for row in audit_rows))
        fake_telemetry_path = out / "llm_telemetry.dryrun_fake.jsonl"
        write_fake_telemetry(fake_telemetry_path)
        validation = validate_effective_trimodel(audit_path, fake_telemetry_path)
        counts = Counter(row["model"] for row in audit_rows)
        result = {
            "case_file": str(case_file),
            "agent_config_source": source,
            "agent_count": len(agent_configs),
            "model_map": str(map_path),
            "assignment_counts": dict(counts),
            "validation_on_fake_telemetry": validation,
            "note": "dry-run only; fake telemetry is not model output and only validates the local validator/export path",
        }
        write_json(out / "dry_run_summary.json", result)
        results.append(result)
    write_json(out_root / "summary.json", {"mode": "dry-run", "started_at": utc_now(), "results": results})
    print(json.dumps({"out_root": str(out_root), "results": results}, ensure_ascii=False, indent=2))
    return 0


def require_execute_keys() -> None:
    missing = [k for k in ("OPENROUTER_API_KEY", "DEEPINFRA_API_KEY") if not os.environ.get(k)]
    if missing:
        raise RuntimeError(f"Missing required key env vars for --execute: {', '.join(missing)}")
    os.environ.setdefault("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1")
    os.environ.setdefault("DEEPINFRA_BASE_URL", "https://api.deepinfra.com/v1/openai")


def backend_env() -> Dict[str, str]:
    env = dict(os.environ)
    env.setdefault("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1")
    env.setdefault("DEEPINFRA_BASE_URL", "https://api.deepinfra.com/v1/openai")
    # Fixed global model for graph/profile/config generation; per-agent map is
    # applied only when the Reddit simulation subprocess starts. Force the
    # backend LLMClient through OpenAI-compatible mode so DeepInfra's raw model
    # id is not misinterpreted as Prompture's native Google provider.
    if env.get("DEEPINFRA_API_KEY"):
        env["MIROFISH_LLM_BACKEND"] = "openai"
        env["LLM_API_KEY"] = env["DEEPINFRA_API_KEY"]
        env["OPENAI_API_KEY"] = env["DEEPINFRA_API_KEY"]
        env["LLM_BASE_URL"] = env["DEEPINFRA_BASE_URL"]
        env["LLM_MODEL_NAME"] = "google/gemma-3-27b-it"
        env["GRAPHITI_LLM_API_KEY"] = env["DEEPINFRA_API_KEY"]
        env["GRAPHITI_LLM_BASE_URL"] = env["DEEPINFRA_BASE_URL"]
        env["GRAPHITI_LLM_MODEL"] = "google/gemma-3-27b-it"
        env["GRAPHITI_LLM_SMALL_MODEL"] = "google/gemma-3-27b-it"
        env["GRAPHITI_LLM_CLIENT_MODE"] = "generic"
        env["GRAPHITI_RERANKER_API_KEY"] = env["DEEPINFRA_API_KEY"]
        env["GRAPHITI_RERANKER_BASE_URL"] = env["DEEPINFRA_BASE_URL"]
        env["GRAPHITI_RERANKER_MODEL"] = "google/gemma-3-27b-it"
    env.setdefault("GRAPH_BACKEND", "graphiti")
    env.setdefault("GRAPHITI_URI", "bolt://localhost:7687")
    env.setdefault("GRAPHITI_USER", "neo4j")
    env.setdefault("GRAPHITI_PASSWORD", "mirofishpassword")
    env.setdefault("GRAPHITI_DATABASE", "neo4j")
    env["GRAPHITI_EMBEDDER_API_KEY"] = "ollama"
    env["GRAPHITI_EMBEDDER_BASE_URL"] = "http://127.0.0.1:11434/v1"
    env["GRAPHITI_EMBEDDER_MODEL"] = "bge-m3"
    env["GRAPHITI_EMBEDDER_DIM"] = "1024"
    env.setdefault("FLASK_HOST", "127.0.0.1")
    env.setdefault("FLASK_PORT", "5001")
    env.setdefault("FLASK_DEBUG", "false")
    env.setdefault("PYTHONUNBUFFERED", "1")
    env.setdefault("OASIS_SEMAPHORE", "2")
    return env


def start_backend(env: Dict[str, str], out: Path) -> subprocess.Popen[str]:
    out.mkdir(parents=True, exist_ok=True)
    return subprocess.Popen(
        [str(PY), "backend/run.py"],
        cwd=REPO,
        env=env,
        stdout=(out / "backend_stdout.log").open("w", encoding="utf-8"),
        stderr=(out / "backend_stderr.log").open("w", encoding="utf-8"),
        text=True,
        start_new_session=(os.name != "nt"),
        creationflags=subprocess.CREATE_NEW_PROCESS_GROUP if os.name == "nt" else 0,
    )


def stop_backend_process(proc: subprocess.Popen[str]) -> None:
    if proc.poll() is not None:
        return
    if os.name == "nt":
        proc.terminate()
        try:
            proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            proc.kill()
        return

    try:
        os.killpg(proc.pid, signal.SIGTERM)
    except ProcessLookupError:
        return
    try:
        proc.wait(timeout=10)
    except subprocess.TimeoutExpired:
        try:
            os.killpg(proc.pid, signal.SIGKILL)
        except ProcessLookupError:
            pass


def wait_backend(base_url: str, timeout: int = 90) -> None:
    client = APIClient(base_url, Path(os.devnull), timeout_seconds=5)
    deadline = time.time() + timeout
    last: Optional[Exception] = None
    while time.time() < deadline:
        try:
            client.request_json("GET", "/health")
            return
        except Exception as exc:  # noqa: BLE001
            last = exc
            time.sleep(1)
    raise TimeoutError(f"backend did not become ready at {base_url}: {last}")


def wait_graph_task(client: APIClient, task_id: str, timeout: int, poll_interval: float) -> Dict[str, Any]:
    deadline = time.time() + timeout
    while time.time() < deadline:
        resp = client.request_json("GET", f"/api/graph/task/{task_id}")
        task = resp.get("data", {})
        status = task.get("status")
        if status in TERMINAL_TASK_STATUSES:
            if status != "completed":
                raise RuntimeError(f"graph task ended with status {status}: {task}")
            return task
        time.sleep(poll_interval)
    raise TimeoutError("graph task polling timed out")


def wait_prepare(client: APIClient, simulation_id: str, task_id: Optional[str], timeout: int, poll_interval: float) -> Dict[str, Any]:
    deadline = time.time() + timeout
    while time.time() < deadline:
        payload: Dict[str, Any] = {"simulation_id": simulation_id}
        if task_id:
            payload["task_id"] = task_id
        resp = client.request_json("POST", "/api/simulation/prepare/status", payload)
        task = resp.get("data", {})
        status = task.get("status")
        if status in {"ready", "completed"}:
            return task
        if status in {"failed", "cancelled", "error"}:
            raise RuntimeError(f"prepare ended with status {status}: {task}")
        time.sleep(poll_interval)
    raise TimeoutError("prepare polling timed out")


def wait_run(client: APIClient, simulation_id: str, timeout: int, poll_interval: float) -> Dict[str, Any]:
    deadline = time.time() + timeout
    last: Dict[str, Any] = {}
    while time.time() < deadline:
        resp = client.request_json("GET", f"/api/simulation/{simulation_id}/run-status")
        last = resp.get("data", {})
        status = last.get("runner_status")
        if status in TERMINAL_RUN_STATUSES:
            return last
        time.sleep(poll_interval)
    raise TimeoutError(f"simulation run polling timed out; last={last}")


def run_entropy(sim_dir: Path, label: str, out: Path) -> Dict[str, Any]:
    commands = {
        "pooled": [str(PY), "backend/scripts/entropy_phase2_analysis.py", "--sim-dir", str(sim_dir), "--label", f"{label}-trimodel-pooled", "--with-embeddings", "--real-embedder", "--output", str(out / f"phase2_{label}_trimodel_pooled.json")],
        "postsonly": [str(PY), "backend/scripts/entropy_phase2_analysis.py", "--sim-dir", str(sim_dir), "--label", f"{label}-trimodel-postsonly", "--with-embeddings", "--real-embedder", "--no-comments", "--output", str(out / f"phase2_{label}_trimodel_postsonly.json")],
    }
    result = {}
    for name, cmd in commands.items():
        cp = subprocess.run(cmd, cwd=REPO, text=True, capture_output=True, timeout=1800)
        (out / f"entropy_{name}.stdout.log").write_text(cp.stdout, encoding="utf-8")
        (out / f"entropy_{name}.stderr.log").write_text(cp.stderr, encoding="utf-8")
        result[name] = {"exit_code": cp.returncode, "command": cmd, "output": cmd[-1]}
    return result


def execute_case(args: argparse.Namespace, client: APIClient, case_file: Path, out: Path) -> Dict[str, Any]:
    out.mkdir(parents=True, exist_ok=True)
    started_at = utc_now()
    ontology = client.post_multipart(
        "/api/graph/ontology/generate",
        fields={"simulation_requirement": args.requirement, "project_name": f"Linea6 trimodel {case_slug(case_file)}"},
        files=[case_file],
        retry=True,
        max_retries=3,
    )
    project_id = ontology.get("data", {}).get("project_id")
    if not project_id:
        raise RuntimeError(f"ontology/generate did not return project_id: {ontology}")
    graph_payload: Dict[str, Any] = {"project_id": project_id}
    if args.graph_chunk_size:
        graph_payload["chunk_size"] = args.graph_chunk_size
    graph_build = client.request_json("POST", "/api/graph/build", graph_payload, retry=True)
    graph_task_id = graph_build.get("data", {}).get("task_id")
    wait_graph_task(client, graph_task_id, args.poll_timeout, args.poll_interval)
    project = client.request_json("GET", f"/api/graph/project/{project_id}")
    graph_id = project.get("data", {}).get("graph_id")
    create = client.request_json("POST", "/api/simulation/create", {"project_id": project_id, "graph_id": graph_id, "enable_twitter": True, "enable_reddit": True}, retry=True)
    simulation_id = create.get("data", {}).get("simulation_id")
    prepare = client.request_json("POST", "/api/simulation/prepare", {"simulation_id": simulation_id, "use_llm_for_profiles": True, "parallel_profile_count": args.parallel_profile_count}, retry=True)
    wait_prepare(client, simulation_id, prepare.get("data", {}).get("task_id"), args.poll_timeout, args.poll_interval)

    sim_dir = REPO / "backend/uploads/simulations" / simulation_id
    agent_configs = load_agent_configs_from_sim_dir(sim_dir)
    model_map = build_round_robin_model_map(agent_configs)
    sim_map = sim_dir / "model_map_linea6_trimodel.generated.yaml"
    out_map = out / "model_map.generated.yaml"
    write_model_map(sim_map, model_map)
    write_model_map(out_map, model_map)

    start_payload = {
        "simulation_id": simulation_id,
        "platform": "reddit",
        "force": True,
        "enable_graph_memory_update": False,
        "no_wait": True,
        "max_rounds": args.rounds,
        "model_map_path": str(sim_map),
    }
    client.request_json("POST", "/api/simulation/start", start_payload, retry=True)
    final_run = wait_run(client, simulation_id, args.poll_timeout, args.poll_interval)

    audit_path = sim_dir / "model_routing_audit.jsonl"
    telemetry_path = sim_dir / "llm_telemetry.jsonl"
    summary_path = out / "llm_telemetry_summary.json"
    validation = validate_effective_trimodel(audit_path, telemetry_path)
    write_json(summary_path, validation["telemetry_summary"])
    write_json(out / "trimodel_validation.json", validation)
    for artifact in [audit_path, telemetry_path, sim_dir / "simulation.log", sim_dir / "reddit_simulation.db", sim_dir / "simulation_config.json", sim_dir / "reddit_profiles.json"]:
        if artifact.exists():
            shutil.copy2(artifact, out / artifact.name)
    entropy = {}
    if final_run.get("runner_status") == "completed" and telemetry_path.exists():
        entropy = run_entropy(sim_dir, case_slug(case_file), out)
    manifest = {
        "started_at": started_at,
        "completed_at": utc_now(),
        "case_file": str(case_file),
        "project_id": project_id,
        "graph_id": graph_id,
        "simulation_id": simulation_id,
        "sim_dir": str(sim_dir),
        "rounds_requested": args.rounds,
        "final_run": final_run,
        "model_map_path": str(sim_map),
        "is_assigned_trimodel": validation["is_assigned_trimodel"],
        "is_effective_trimodel": validation["is_effective_trimodel"],
        "entropy": entropy,
    }
    write_json(out / "run_manifest.json", manifest)
    return manifest


def execute(args: argparse.Namespace, out_root: Path) -> int:
    require_execute_keys()
    out_root.mkdir(parents=True, exist_ok=True)
    backend_proc: Optional[subprocess.Popen[str]] = None
    try:
        if args.start_backend:
            env = backend_env()
            write_json(
                out_root / "backend_env_sanitized.json",
                {
                    "LLM_MODEL_NAME": env.get("LLM_MODEL_NAME"),
                    "LLM_BASE_URL": env.get("LLM_BASE_URL"),
                    "GRAPHITI_LLM_MODEL": env.get("GRAPHITI_LLM_MODEL"),
                    "GRAPHITI_LLM_BASE_URL": env.get("GRAPHITI_LLM_BASE_URL"),
                    "OASIS_SEMAPHORE": env.get("OASIS_SEMAPHORE"),
                    "OPENROUTER_API_KEY": "<set>" if env.get("OPENROUTER_API_KEY") else "<unset>",
                    "DEEPINFRA_API_KEY": "<set>" if env.get("DEEPINFRA_API_KEY") else "<unset>",
                },
            )
            backend_proc = start_backend(env, out_root)
            wait_backend(args.base_url, timeout=120)
        client = APIClient(args.base_url, out_root / "request_trace.json", timeout_seconds=300, accept_language="es")
        manifests = []
        for case_file in expand_cases(args):
            manifests.append(execute_case(args, client, case_file, out_root / case_slug(case_file)))
            write_json(out_root / "summary.json", {"mode": "execute", "results": manifests})
        ok = all(m.get("is_effective_trimodel") for m in manifests)
        return 0 if ok else 2
    finally:
        if backend_proc is not None:
            stop_backend_process(backend_proc)


def expand_cases(args: argparse.Namespace) -> List[Path]:
    if args.all_temporal_packs:
        names = ["seed_T0.md", "seed_T1.md", "seed_T2.md", "seed_T3.md", "seed_T3_clean.md"]
        return [DEFAULT_CASE_DIR / name for name in names]
    return [Path(p).resolve() for p in (args.case_file or [DEFAULT_CASE])]


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Línea 6 tri-model single-simulation runner using model_map_path")
    parser.add_argument("--case-file", action="append", type=Path, help="Seed file. Repeat for multiple cases. Defaults to seed_T3_clean.md")
    parser.add_argument("--all-temporal-packs", action="store_true", help="Run T0/T1/T2/T3/T3_clean")
    parser.add_argument("--out-root", type=Path, default=None)
    parser.add_argument("--execute", action="store_true", help="Perform paid real backend run. Default is no-key dry-run.")
    parser.add_argument("--start-backend", action="store_true", help="Start backend/run.py with a sanitized Gemma/DeepInfra prepare env.")
    parser.add_argument("--base-url", default="http://127.0.0.1:5001")
    parser.add_argument("--rounds", type=int, default=48)
    parser.add_argument("--poll-timeout", type=int, default=7200)
    parser.add_argument("--poll-interval", type=float, default=2.0)
    parser.add_argument("--graph-chunk-size", type=int, default=3000)
    parser.add_argument("--parallel-profile-count", type=int, default=5)
    parser.add_argument("--requirement", default=DEFAULT_REQUIREMENT)
    parser.add_argument("--prepared-sim-dir", type=Path, default=None, help="Dry-run against an existing prepared sim dir instead of synthetic agents.")
    parser.add_argument("--synthetic-agents", type=int, default=12, help="Synthetic dry-run agent count when no prepared sim dir is provided.")
    args = parser.parse_args(argv)

    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    out_root = args.out_root or DEFAULT_OUT_ROOT / f"trimodel_model_map_{stamp}"
    if args.execute:
        try:
            return execute(args, out_root)
        except RuntimeError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 1
    return dry_run(args, out_root)


if __name__ == "__main__":
    raise SystemExit(main())
